//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace MvcAppHylinedoBrasilMobile.Models.bdApolo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CIDADE))]
    [KnownType(typeof(CTRL_LOTE))]
    [KnownType(typeof(FIC_TEC_PROD))]
    [KnownType(typeof(ITEM_CTRL_INV1))]
    [KnownType(typeof(PRODUTO1))]
    [KnownType(typeof(PRODUTO))]
    public partial class PRODUTO1: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string ProdCodEstr
        {
            get { return _prodCodEstr; }
            set
            {
                if (_prodCodEstr != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ProdCodEstr' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PRODUTO != null && PRODUTO.ProdCodEstr != value)
                        {
                            PRODUTO = null;
                        }
                    }
                    _prodCodEstr = value;
                    OnPropertyChanged("ProdCodEstr");
                }
            }
        }
        private string _prodCodEstr;
    
        [DataMember]
        public string ProdVisPocket
        {
            get { return _prodVisPocket; }
            set
            {
                if (_prodVisPocket != value)
                {
                    _prodVisPocket = value;
                    OnPropertyChanged("ProdVisPocket");
                }
            }
        }
        private string _prodVisPocket;
    
        [DataMember]
        public Nullable<System.DateTime> ProdUltDataMod
        {
            get { return _prodUltDataMod; }
            set
            {
                if (_prodUltDataMod != value)
                {
                    _prodUltDataMod = value;
                    OnPropertyChanged("ProdUltDataMod");
                }
            }
        }
        private Nullable<System.DateTime> _prodUltDataMod;
    
        [DataMember]
        public string ProdServMobilDesmobil
        {
            get { return _prodServMobilDesmobil; }
            set
            {
                if (_prodServMobilDesmobil != value)
                {
                    _prodServMobilDesmobil = value;
                    OnPropertyChanged("ProdServMobilDesmobil");
                }
            }
        }
        private string _prodServMobilDesmobil;
    
        [DataMember]
        public string ProdEntraCalcVerbaProjeto
        {
            get { return _prodEntraCalcVerbaProjeto; }
            set
            {
                if (_prodEntraCalcVerbaProjeto != value)
                {
                    _prodEntraCalcVerbaProjeto = value;
                    OnPropertyChanged("ProdEntraCalcVerbaProjeto");
                }
            }
        }
        private string _prodEntraCalcVerbaProjeto;
    
        [DataMember]
        public string ProdTipoTabPV
        {
            get { return _prodTipoTabPV; }
            set
            {
                if (_prodTipoTabPV != value)
                {
                    _prodTipoTabPV = value;
                    OnPropertyChanged("ProdTipoTabPV");
                }
            }
        }
        private string _prodTipoTabPV;
    
        [DataMember]
        public string ProdCidCodBloq
        {
            get { return _prodCidCodBloq; }
            set
            {
                if (_prodCidCodBloq != value)
                {
                    ChangeTracker.RecordOriginalValue("ProdCidCodBloq", _prodCidCodBloq);
                    if (!IsDeserializing)
                    {
                        if (CIDADE != null && CIDADE.CidCod != value)
                        {
                            CIDADE = null;
                        }
                    }
                    _prodCidCodBloq = value;
                    OnPropertyChanged("ProdCidCodBloq");
                }
            }
        }
        private string _prodCidCodBloq;
    
        [DataMember]
        public string ProdPrefer
        {
            get { return _prodPrefer; }
            set
            {
                if (_prodPrefer != value)
                {
                    _prodPrefer = value;
                    OnPropertyChanged("ProdPrefer");
                }
            }
        }
        private string _prodPrefer;
    
        [DataMember]
        public string ProdVisualReembOnline
        {
            get { return _prodVisualReembOnline; }
            set
            {
                if (_prodVisualReembOnline != value)
                {
                    _prodVisualReembOnline = value;
                    OnPropertyChanged("ProdVisualReembOnline");
                }
            }
        }
        private string _prodVisualReembOnline;
    
        [DataMember]
        public string ProdRetPermSelManualCarga
        {
            get { return _prodRetPermSelManualCarga; }
            set
            {
                if (_prodRetPermSelManualCarga != value)
                {
                    _prodRetPermSelManualCarga = value;
                    OnPropertyChanged("ProdRetPermSelManualCarga");
                }
            }
        }
        private string _prodRetPermSelManualCarga;
    
        [DataMember]
        public string ProdGeraReqMatTransf
        {
            get { return _prodGeraReqMatTransf; }
            set
            {
                if (_prodGeraReqMatTransf != value)
                {
                    _prodGeraReqMatTransf = value;
                    OnPropertyChanged("ProdGeraReqMatTransf");
                }
            }
        }
        private string _prodGeraReqMatTransf;
    
        [DataMember]
        public string ProdObrigRelacLoteOP
        {
            get { return _prodObrigRelacLoteOP; }
            set
            {
                if (_prodObrigRelacLoteOP != value)
                {
                    _prodObrigRelacLoteOP = value;
                    OnPropertyChanged("ProdObrigRelacLoteOP");
                }
            }
        }
        private string _prodObrigRelacLoteOP;
    
        [DataMember]
        public string ProdModoAtualizacao
        {
            get { return _prodModoAtualizacao; }
            set
            {
                if (_prodModoAtualizacao != value)
                {
                    _prodModoAtualizacao = value;
                    OnPropertyChanged("ProdModoAtualizacao");
                }
            }
        }
        private string _prodModoAtualizacao;
    
        [DataMember]
        public string ProdPossuiTarget
        {
            get { return _prodPossuiTarget; }
            set
            {
                if (_prodPossuiTarget != value)
                {
                    _prodPossuiTarget = value;
                    OnPropertyChanged("ProdPossuiTarget");
                }
            }
        }
        private string _prodPossuiTarget;
    
        [DataMember]
        public string ProdCalcQtdPorParticipItOS
        {
            get { return _prodCalcQtdPorParticipItOS; }
            set
            {
                if (_prodCalcQtdPorParticipItOS != value)
                {
                    _prodCalcQtdPorParticipItOS = value;
                    OnPropertyChanged("ProdCalcQtdPorParticipItOS");
                }
            }
        }
        private string _prodCalcQtdPorParticipItOS;
    
        [DataMember]
        public string ProdCorteDedo
        {
            get { return _prodCorteDedo; }
            set
            {
                if (_prodCorteDedo != value)
                {
                    _prodCorteDedo = value;
                    OnPropertyChanged("ProdCorteDedo");
                }
            }
        }
        private string _prodCorteDedo;
    
        [DataMember]
        public string ProdCodEnquadIPI
        {
            get { return _prodCodEnquadIPI; }
            set
            {
                if (_prodCodEnquadIPI != value)
                {
                    _prodCodEnquadIPI = value;
                    OnPropertyChanged("ProdCodEnquadIPI");
                }
            }
        }
        private string _prodCodEnquadIPI;
    
        [DataMember]
        public string ProdCodSeloControleIPI
        {
            get { return _prodCodSeloControleIPI; }
            set
            {
                if (_prodCodSeloControleIPI != value)
                {
                    _prodCodSeloControleIPI = value;
                    OnPropertyChanged("ProdCodSeloControleIPI");
                }
            }
        }
        private string _prodCodSeloControleIPI;
    
        [DataMember]
        public string ProdEntraRegInventSpedSinteg
        {
            get { return _prodEntraRegInventSpedSinteg; }
            set
            {
                if (_prodEntraRegInventSpedSinteg != value)
                {
                    _prodEntraRegInventSpedSinteg = value;
                    OnPropertyChanged("ProdEntraRegInventSpedSinteg");
                }
            }
        }
        private string _prodEntraRegInventSpedSinteg;
    
        [DataMember]
        public string ProdCodEstrProdPaiProj
        {
            get { return _prodCodEstrProdPaiProj; }
            set
            {
                if (_prodCodEstrProdPaiProj != value)
                {
                    ChangeTracker.RecordOriginalValue("ProdCodEstrProdPaiProj", _prodCodEstrProdPaiProj);
                    if (!IsDeserializing)
                    {
                        if (PRODUTO12 != null && PRODUTO12.ProdCodEstr != value)
                        {
                            PRODUTO12 = null;
                        }
                    }
                    _prodCodEstrProdPaiProj = value;
                    OnPropertyChanged("ProdCodEstrProdPaiProj");
                }
            }
        }
        private string _prodCodEstrProdPaiProj;
    
        [DataMember]
        public string ProdImprimeNumSerNFe
        {
            get { return _prodImprimeNumSerNFe; }
            set
            {
                if (_prodImprimeNumSerNFe != value)
                {
                    _prodImprimeNumSerNFe = value;
                    OnPropertyChanged("ProdImprimeNumSerNFe");
                }
            }
        }
        private string _prodImprimeNumSerNFe;
    
        [DataMember]
        public string ProdTabIncidPisCofinsCod
        {
            get { return _prodTabIncidPisCofinsCod; }
            set
            {
                if (_prodTabIncidPisCofinsCod != value)
                {
                    _prodTabIncidPisCofinsCod = value;
                    OnPropertyChanged("ProdTabIncidPisCofinsCod");
                }
            }
        }
        private string _prodTabIncidPisCofinsCod;
    
        [DataMember]
        public string ProdCodGrupoIncidPisCofins
        {
            get { return _prodCodGrupoIncidPisCofins; }
            set
            {
                if (_prodCodGrupoIncidPisCofins != value)
                {
                    _prodCodGrupoIncidPisCofins = value;
                    OnPropertyChanged("ProdCodGrupoIncidPisCofins");
                }
            }
        }
        private string _prodCodGrupoIncidPisCofins;
    
        [DataMember]
        public string ProdMarcaComerc
        {
            get { return _prodMarcaComerc; }
            set
            {
                if (_prodMarcaComerc != value)
                {
                    _prodMarcaComerc = value;
                    OnPropertyChanged("ProdMarcaComerc");
                }
            }
        }
        private string _prodMarcaComerc;
    
        [DataMember]
        public string ProdTaxaDuBruLiq
        {
            get { return _prodTaxaDuBruLiq; }
            set
            {
                if (_prodTaxaDuBruLiq != value)
                {
                    _prodTaxaDuBruLiq = value;
                    OnPropertyChanged("ProdTaxaDuBruLiq");
                }
            }
        }
        private string _prodTaxaDuBruLiq;
    
        [DataMember]
        public string MarcaProdCodObjVend
        {
            get { return _marcaProdCodObjVend; }
            set
            {
                if (_marcaProdCodObjVend != value)
                {
                    _marcaProdCodObjVend = value;
                    OnPropertyChanged("MarcaProdCodObjVend");
                }
            }
        }
        private string _marcaProdCodObjVend;
    
        [DataMember]
        public string GrpProdCodObjVend
        {
            get { return _grpProdCodObjVend; }
            set
            {
                if (_grpProdCodObjVend != value)
                {
                    _grpProdCodObjVend = value;
                    OnPropertyChanged("GrpProdCodObjVend");
                }
            }
        }
        private string _grpProdCodObjVend;
    
        [DataMember]
        public string ProdCtrlCustoFIFO
        {
            get { return _prodCtrlCustoFIFO; }
            set
            {
                if (_prodCtrlCustoFIFO != value)
                {
                    _prodCtrlCustoFIFO = value;
                    OnPropertyChanged("ProdCtrlCustoFIFO");
                }
            }
        }
        private string _prodCtrlCustoFIFO;
    
        [DataMember]
        public string ProdDeduzICMSSegCusto
        {
            get { return _prodDeduzICMSSegCusto; }
            set
            {
                if (_prodDeduzICMSSegCusto != value)
                {
                    _prodDeduzICMSSegCusto = value;
                    OnPropertyChanged("ProdDeduzICMSSegCusto");
                }
            }
        }
        private string _prodDeduzICMSSegCusto;
    
        [DataMember]
        public string ProdDeduzICMSSTSegCusto
        {
            get { return _prodDeduzICMSSTSegCusto; }
            set
            {
                if (_prodDeduzICMSSTSegCusto != value)
                {
                    _prodDeduzICMSSTSegCusto = value;
                    OnPropertyChanged("ProdDeduzICMSSTSegCusto");
                }
            }
        }
        private string _prodDeduzICMSSTSegCusto;
    
        [DataMember]
        public string ProdDeduzIPISegCusto
        {
            get { return _prodDeduzIPISegCusto; }
            set
            {
                if (_prodDeduzIPISegCusto != value)
                {
                    _prodDeduzIPISegCusto = value;
                    OnPropertyChanged("ProdDeduzIPISegCusto");
                }
            }
        }
        private string _prodDeduzIPISegCusto;
    
        [DataMember]
        public string ProdDeduzPISSegCusto
        {
            get { return _prodDeduzPISSegCusto; }
            set
            {
                if (_prodDeduzPISSegCusto != value)
                {
                    _prodDeduzPISSegCusto = value;
                    OnPropertyChanged("ProdDeduzPISSegCusto");
                }
            }
        }
        private string _prodDeduzPISSegCusto;
    
        [DataMember]
        public string ProdDeduzCOFINSSegCusto
        {
            get { return _prodDeduzCOFINSSegCusto; }
            set
            {
                if (_prodDeduzCOFINSSegCusto != value)
                {
                    _prodDeduzCOFINSSegCusto = value;
                    OnPropertyChanged("ProdDeduzCOFINSSegCusto");
                }
            }
        }
        private string _prodDeduzCOFINSSegCusto;
    
        [DataMember]
        public string ProdCertificado
        {
            get { return _prodCertificado; }
            set
            {
                if (_prodCertificado != value)
                {
                    _prodCertificado = value;
                    OnPropertyChanged("ProdCertificado");
                }
            }
        }
        private string _prodCertificado;
    
        [DataMember]
        public string ProdTurDataBase
        {
            get { return _prodTurDataBase; }
            set
            {
                if (_prodTurDataBase != value)
                {
                    _prodTurDataBase = value;
                    OnPropertyChanged("ProdTurDataBase");
                }
            }
        }
        private string _prodTurDataBase;
    
        [DataMember]
        public string ProdBloqVendConectExterno
        {
            get { return _prodBloqVendConectExterno; }
            set
            {
                if (_prodBloqVendConectExterno != value)
                {
                    _prodBloqVendConectExterno = value;
                    OnPropertyChanged("ProdBloqVendConectExterno");
                }
            }
        }
        private string _prodBloqVendConectExterno;
    
        [DataMember]
        public string ProdCodMS
        {
            get { return _prodCodMS; }
            set
            {
                if (_prodCodMS != value)
                {
                    _prodCodMS = value;
                    OnPropertyChanged("ProdCodMS");
                }
            }
        }
        private string _prodCodMS;
    
        [DataMember]
        public string ProdEntraCalcQtdTotVenda
        {
            get { return _prodEntraCalcQtdTotVenda; }
            set
            {
                if (_prodEntraCalcQtdTotVenda != value)
                {
                    _prodEntraCalcQtdTotVenda = value;
                    OnPropertyChanged("ProdEntraCalcQtdTotVenda");
                }
            }
        }
        private string _prodEntraCalcQtdTotVenda;
    
        [DataMember]
        public string ProdCodART
        {
            get { return _prodCodART; }
            set
            {
                if (_prodCodART != value)
                {
                    _prodCodART = value;
                    OnPropertyChanged("ProdCodART");
                }
            }
        }
        private string _prodCodART;
    
        [DataMember]
        public string ProdVacina
        {
            get { return _prodVacina; }
            set
            {
                if (_prodVacina != value)
                {
                    _prodVacina = value;
                    OnPropertyChanged("ProdVacina");
                }
            }
        }
        private string _prodVacina;
    
        [DataMember]
        public string ProdNecessitaCA
        {
            get { return _prodNecessitaCA; }
            set
            {
                if (_prodNecessitaCA != value)
                {
                    _prodNecessitaCA = value;
                    OnPropertyChanged("ProdNecessitaCA");
                }
            }
        }
        private string _prodNecessitaCA;
    
        [DataMember]
        public string RegraPagtoEntCod
        {
            get { return _regraPagtoEntCod; }
            set
            {
                if (_regraPagtoEntCod != value)
                {
                    _regraPagtoEntCod = value;
                    OnPropertyChanged("RegraPagtoEntCod");
                }
            }
        }
        private string _regraPagtoEntCod;
    
        [DataMember]
        public string DesCodEstr
        {
            get { return _desCodEstr; }
            set
            {
                if (_desCodEstr != value)
                {
                    _desCodEstr = value;
                    OnPropertyChanged("DesCodEstr");
                }
            }
        }
        private string _desCodEstr;
    
        [DataMember]
        public string ProdEntEstqApontUltOper
        {
            get { return _prodEntEstqApontUltOper; }
            set
            {
                if (_prodEntEstqApontUltOper != value)
                {
                    _prodEntEstqApontUltOper = value;
                    OnPropertyChanged("ProdEntEstqApontUltOper");
                }
            }
        }
        private string _prodEntEstqApontUltOper;
    
        [DataMember]
        public Nullable<decimal> ProdPercTotAproxImpost
        {
            get { return _prodPercTotAproxImpost; }
            set
            {
                if (_prodPercTotAproxImpost != value)
                {
                    _prodPercTotAproxImpost = value;
                    OnPropertyChanged("ProdPercTotAproxImpost");
                }
            }
        }
        private Nullable<decimal> _prodPercTotAproxImpost;
    
        [DataMember]
        public string PRODSTATDMI
        {
            get { return _pRODSTATDMI; }
            set
            {
                if (_pRODSTATDMI != value)
                {
                    _pRODSTATDMI = value;
                    OnPropertyChanged("PRODSTATDMI");
                }
            }
        }
        private string _pRODSTATDMI;
    
        [DataMember]
        public string RefPautaCod
        {
            get { return _refPautaCod; }
            set
            {
                if (_refPautaCod != value)
                {
                    _refPautaCod = value;
                    OnPropertyChanged("RefPautaCod");
                }
            }
        }
        private string _refPautaCod;
    
        [DataMember]
        public string ProdFabricProp
        {
            get { return _prodFabricProp; }
            set
            {
                if (_prodFabricProp != value)
                {
                    _prodFabricProp = value;
                    OnPropertyChanged("ProdFabricProp");
                }
            }
        }
        private string _prodFabricProp;
    
        [DataMember]
        public string ProdBenefic
        {
            get { return _prodBenefic; }
            set
            {
                if (_prodBenefic != value)
                {
                    _prodBenefic = value;
                    OnPropertyChanged("ProdBenefic");
                }
            }
        }
        private string _prodBenefic;
    
        [DataMember]
        public Nullable<decimal> ProdHotelQtdEstrela
        {
            get { return _prodHotelQtdEstrela; }
            set
            {
                if (_prodHotelQtdEstrela != value)
                {
                    _prodHotelQtdEstrela = value;
                    OnPropertyChanged("ProdHotelQtdEstrela");
                }
            }
        }
        private Nullable<decimal> _prodHotelQtdEstrela;
    
        [DataMember]
        public string ProdTerc
        {
            get { return _prodTerc; }
            set
            {
                if (_prodTerc != value)
                {
                    _prodTerc = value;
                    OnPropertyChanged("ProdTerc");
                }
            }
        }
        private string _prodTerc;
    
        [DataMember]
        public string PRODCTRLCARGAORDEMIMPRESS
        {
            get { return _pRODCTRLCARGAORDEMIMPRESS; }
            set
            {
                if (_pRODCTRLCARGAORDEMIMPRESS != value)
                {
                    _pRODCTRLCARGAORDEMIMPRESS = value;
                    OnPropertyChanged("PRODCTRLCARGAORDEMIMPRESS");
                }
            }
        }
        private string _pRODCTRLCARGAORDEMIMPRESS;
    
        [DataMember]
        public Nullable<System.DateTime> ProdDtUltAtualiz
        {
            get { return _prodDtUltAtualiz; }
            set
            {
                if (_prodDtUltAtualiz != value)
                {
                    _prodDtUltAtualiz = value;
                    OnPropertyChanged("ProdDtUltAtualiz");
                }
            }
        }
        private Nullable<System.DateTime> _prodDtUltAtualiz;
    
        [DataMember]
        public Nullable<decimal> ProdPesoFixoMaximo
        {
            get { return _prodPesoFixoMaximo; }
            set
            {
                if (_prodPesoFixoMaximo != value)
                {
                    _prodPesoFixoMaximo = value;
                    OnPropertyChanged("ProdPesoFixoMaximo");
                }
            }
        }
        private Nullable<decimal> _prodPesoFixoMaximo;
    
        [DataMember]
        public string ProdObrigEmbAtendPv
        {
            get { return _prodObrigEmbAtendPv; }
            set
            {
                if (_prodObrigEmbAtendPv != value)
                {
                    _prodObrigEmbAtendPv = value;
                    OnPropertyChanged("ProdObrigEmbAtendPv");
                }
            }
        }
        private string _prodObrigEmbAtendPv;
    
        [DataMember]
        public string ProdNomeRelat
        {
            get { return _prodNomeRelat; }
            set
            {
                if (_prodNomeRelat != value)
                {
                    _prodNomeRelat = value;
                    OnPropertyChanged("ProdNomeRelat");
                }
            }
        }
        private string _prodNomeRelat;
    
        [DataMember]
        public string ProdNecessitaSSCC
        {
            get { return _prodNecessitaSSCC; }
            set
            {
                if (_prodNecessitaSSCC != value)
                {
                    _prodNecessitaSSCC = value;
                    OnPropertyChanged("ProdNecessitaSSCC");
                }
            }
        }
        private string _prodNecessitaSSCC;
    
        [DataMember]
        public string ProdDesconsidPesagem
        {
            get { return _prodDesconsidPesagem; }
            set
            {
                if (_prodDesconsidPesagem != value)
                {
                    _prodDesconsidPesagem = value;
                    OnPropertyChanged("ProdDesconsidPesagem");
                }
            }
        }
        private string _prodDesconsidPesagem;
    
        [DataMember]
        public string PRODNOMERELAT2
        {
            get { return _pRODNOMERELAT2; }
            set
            {
                if (_pRODNOMERELAT2 != value)
                {
                    _pRODNOMERELAT2 = value;
                    OnPropertyChanged("PRODNOMERELAT2");
                }
            }
        }
        private string _pRODNOMERELAT2;
    
        [DataMember]
        public string PRODPATHARQUIVO2
        {
            get { return _pRODPATHARQUIVO2; }
            set
            {
                if (_pRODPATHARQUIVO2 != value)
                {
                    _pRODPATHARQUIVO2 = value;
                    OnPropertyChanged("PRODPATHARQUIVO2");
                }
            }
        }
        private string _pRODPATHARQUIVO2;
    
        [DataMember]
        public string PRODOPFINALIZAPONTQTDNEC
        {
            get { return _pRODOPFINALIZAPONTQTDNEC; }
            set
            {
                if (_pRODOPFINALIZAPONTQTDNEC != value)
                {
                    _pRODOPFINALIZAPONTQTDNEC = value;
                    OnPropertyChanged("PRODOPFINALIZAPONTQTDNEC");
                }
            }
        }
        private string _pRODOPFINALIZAPONTQTDNEC;
    
        [DataMember]
        public string USERCodigoCHIC
        {
            get { return _uSERCodigoCHIC; }
            set
            {
                if (_uSERCodigoCHIC != value)
                {
                    _uSERCodigoCHIC = value;
                    OnPropertyChanged("USERCodigoCHIC");
                }
            }
        }
        private string _uSERCodigoCHIC;
    
        [DataMember]
        public string USEREmpresaLinha
        {
            get { return _uSEREmpresaLinha; }
            set
            {
                if (_uSEREmpresaLinha != value)
                {
                    _uSEREmpresaLinha = value;
                    OnPropertyChanged("USEREmpresaLinha");
                }
            }
        }
        private string _uSEREmpresaLinha;
    
        [DataMember]
        public string USERLinhagemRRC
        {
            get { return _uSERLinhagemRRC; }
            set
            {
                if (_uSERLinhagemRRC != value)
                {
                    _uSERLinhagemRRC = value;
                    OnPropertyChanged("USERLinhagemRRC");
                }
            }
        }
        private string _uSERLinhagemRRC;
    
        [DataMember]
        public Nullable<short> USERNumFormula
        {
            get { return _uSERNumFormula; }
            set
            {
                if (_uSERNumFormula != value)
                {
                    _uSERNumFormula = value;
                    OnPropertyChanged("USERNumFormula");
                }
            }
        }
        private Nullable<short> _uSERNumFormula;
    
        [DataMember]
        public Nullable<decimal> USERPpcpKg01Batida
        {
            get { return _uSERPpcpKg01Batida; }
            set
            {
                if (_uSERPpcpKg01Batida != value)
                {
                    _uSERPpcpKg01Batida = value;
                    OnPropertyChanged("USERPpcpKg01Batida");
                }
            }
        }
        private Nullable<decimal> _uSERPpcpKg01Batida;
    
        [DataMember]
        public string USERPRODCODICMSST
        {
            get { return _uSERPRODCODICMSST; }
            set
            {
                if (_uSERPRODCODICMSST != value)
                {
                    _uSERPRODCODICMSST = value;
                    OnPropertyChanged("USERPRODCODICMSST");
                }
            }
        }
        private string _uSERPRODCODICMSST;
    
        [DataMember]
        public Nullable<System.DateTime> USERPRODDATAICMSST
        {
            get { return _uSERPRODDATAICMSST; }
            set
            {
                if (_uSERPRODDATAICMSST != value)
                {
                    _uSERPRODDATAICMSST = value;
                    OnPropertyChanged("USERPRODDATAICMSST");
                }
            }
        }
        private Nullable<System.DateTime> _uSERPRODDATAICMSST;
    
        [DataMember]
        public string USERTipoLancEntradaProd
        {
            get { return _uSERTipoLancEntradaProd; }
            set
            {
                if (_uSERTipoLancEntradaProd != value)
                {
                    _uSERTipoLancEntradaProd = value;
                    OnPropertyChanged("USERTipoLancEntradaProd");
                }
            }
        }
        private string _uSERTipoLancEntradaProd;
    
        [DataMember]
        public string USERTipoLancSaidaProd
        {
            get { return _uSERTipoLancSaidaProd; }
            set
            {
                if (_uSERTipoLancSaidaProd != value)
                {
                    _uSERTipoLancSaidaProd = value;
                    OnPropertyChanged("USERTipoLancSaidaProd");
                }
            }
        }
        private string _uSERTipoLancSaidaProd;
    
        [DataMember]
        public string USERTipoLinha
        {
            get { return _uSERTipoLinha; }
            set
            {
                if (_uSERTipoLinha != value)
                {
                    _uSERTipoLinha = value;
                    OnPropertyChanged("USERTipoLinha");
                }
            }
        }
        private string _uSERTipoLinha;
    
        [DataMember]
        public string USERTLBaixaAdicProd
        {
            get { return _uSERTLBaixaAdicProd; }
            set
            {
                if (_uSERTLBaixaAdicProd != value)
                {
                    _uSERTLBaixaAdicProd = value;
                    OnPropertyChanged("USERTLBaixaAdicProd");
                }
            }
        }
        private string _uSERTLBaixaAdicProd;
    
        [DataMember]
        public string ProdIndEscRelev
        {
            get { return _prodIndEscRelev; }
            set
            {
                if (_prodIndEscRelev != value)
                {
                    _prodIndEscRelev = value;
                    OnPropertyChanged("ProdIndEscRelev");
                }
            }
        }
        private string _prodIndEscRelev;
    
        [DataMember]
        public Nullable<decimal> ProdPesoRateioEstrCusto
        {
            get { return _prodPesoRateioEstrCusto; }
            set
            {
                if (_prodPesoRateioEstrCusto != value)
                {
                    _prodPesoRateioEstrCusto = value;
                    OnPropertyChanged("ProdPesoRateioEstrCusto");
                }
            }
        }
        private Nullable<decimal> _prodPesoRateioEstrCusto;
    
        [DataMember]
        public string ProdObrigAtendRMLibOP
        {
            get { return _prodObrigAtendRMLibOP; }
            set
            {
                if (_prodObrigAtendRMLibOP != value)
                {
                    _prodObrigAtendRMLibOP = value;
                    OnPropertyChanged("ProdObrigAtendRMLibOP");
                }
            }
        }
        private string _prodObrigAtendRMLibOP;
    
        [DataMember]
        public string ProdParticipaSaldoDesmVend
        {
            get { return _prodParticipaSaldoDesmVend; }
            set
            {
                if (_prodParticipaSaldoDesmVend != value)
                {
                    _prodParticipaSaldoDesmVend = value;
                    OnPropertyChanged("ProdParticipaSaldoDesmVend");
                }
            }
        }
        private string _prodParticipaSaldoDesmVend;
    
        [DataMember]
        public Nullable<int> IDTipoServReinf
        {
            get { return _iDTipoServReinf; }
            set
            {
                if (_iDTipoServReinf != value)
                {
                    _iDTipoServReinf = value;
                    OnPropertyChanged("IDTipoServReinf");
                }
            }
        }
        private Nullable<int> _iDTipoServReinf;
    
        [DataMember]
        public string ProdSimilar
        {
            get { return _prodSimilar; }
            set
            {
                if (_prodSimilar != value)
                {
                    _prodSimilar = value;
                    OnPropertyChanged("ProdSimilar");
                }
            }
        }
        private string _prodSimilar;
    
        [DataMember]
        public string ProdNormaAplic
        {
            get { return _prodNormaAplic; }
            set
            {
                if (_prodNormaAplic != value)
                {
                    _prodNormaAplic = value;
                    OnPropertyChanged("ProdNormaAplic");
                }
            }
        }
        private string _prodNormaAplic;
    
        [DataMember]
        public string ProdCodAnvisa
        {
            get { return _prodCodAnvisa; }
            set
            {
                if (_prodCodAnvisa != value)
                {
                    _prodCodAnvisa = value;
                    OnPropertyChanged("ProdCodAnvisa");
                }
            }
        }
        private string _prodCodAnvisa;
    
        [DataMember]
        public string ProdUnidPrNeg
        {
            get { return _prodUnidPrNeg; }
            set
            {
                if (_prodUnidPrNeg != value)
                {
                    _prodUnidPrNeg = value;
                    OnPropertyChanged("ProdUnidPrNeg");
                }
            }
        }
        private string _prodUnidPrNeg;
    
        [DataMember]
        public string ProdDescrANP
        {
            get { return _prodDescrANP; }
            set
            {
                if (_prodDescrANP != value)
                {
                    _prodDescrANP = value;
                    OnPropertyChanged("ProdDescrANP");
                }
            }
        }
        private string _prodDescrANP;
    
        [DataMember]
        public Nullable<decimal> ProdPercGLP
        {
            get { return _prodPercGLP; }
            set
            {
                if (_prodPercGLP != value)
                {
                    _prodPercGLP = value;
                    OnPropertyChanged("ProdPercGLP");
                }
            }
        }
        private Nullable<decimal> _prodPercGLP;
    
        [DataMember]
        public Nullable<decimal> ProdPercGasNatNac
        {
            get { return _prodPercGasNatNac; }
            set
            {
                if (_prodPercGasNatNac != value)
                {
                    _prodPercGasNatNac = value;
                    OnPropertyChanged("ProdPercGasNatNac");
                }
            }
        }
        private Nullable<decimal> _prodPercGasNatNac;
    
        [DataMember]
        public Nullable<decimal> ProdPercGasNatImp
        {
            get { return _prodPercGasNatImp; }
            set
            {
                if (_prodPercGasNatImp != value)
                {
                    _prodPercGasNatImp = value;
                    OnPropertyChanged("ProdPercGasNatImp");
                }
            }
        }
        private Nullable<decimal> _prodPercGasNatImp;
    
        [DataMember]
        public Nullable<decimal> ProdValKgSemICMS
        {
            get { return _prodValKgSemICMS; }
            set
            {
                if (_prodValKgSemICMS != value)
                {
                    _prodValKgSemICMS = value;
                    OnPropertyChanged("ProdValKgSemICMS");
                }
            }
        }
        private Nullable<decimal> _prodValKgSemICMS;
    
        [DataMember]
        public string ProdFabricEscalRelev
        {
            get { return _prodFabricEscalRelev; }
            set
            {
                if (_prodFabricEscalRelev != value)
                {
                    _prodFabricEscalRelev = value;
                    OnPropertyChanged("ProdFabricEscalRelev");
                }
            }
        }
        private string _prodFabricEscalRelev;
    
        [DataMember]
        public string USERInsumoDosado
        {
            get { return _uSERInsumoDosado; }
            set
            {
                if (_uSERInsumoDosado != value)
                {
                    _uSERInsumoDosado = value;
                    OnPropertyChanged("USERInsumoDosado");
                }
            }
        }
        private string _uSERInsumoDosado;
    
        [DataMember]
        public string USERStatusPedidoRacao
        {
            get { return _uSERStatusPedidoRacao; }
            set
            {
                if (_uSERStatusPedidoRacao != value)
                {
                    _uSERStatusPedidoRacao = value;
                    OnPropertyChanged("USERStatusPedidoRacao");
                }
            }
        }
        private string _uSERStatusPedidoRacao;
    
        [DataMember]
        public string USERFaseRacao
        {
            get { return _uSERFaseRacao; }
            set
            {
                if (_uSERFaseRacao != value)
                {
                    _uSERFaseRacao = value;
                    OnPropertyChanged("USERFaseRacao");
                }
            }
        }
        private string _uSERFaseRacao;
    
        [DataMember]
        public string ProdProdutAssocVend
        {
            get { return _prodProdutAssocVend; }
            set
            {
                if (_prodProdutAssocVend != value)
                {
                    _prodProdutAssocVend = value;
                    OnPropertyChanged("ProdProdutAssocVend");
                }
            }
        }
        private string _prodProdutAssocVend;
    
        [DataMember]
        public string PRODPERMLOTEVENCIDO
        {
            get { return _pRODPERMLOTEVENCIDO; }
            set
            {
                if (_pRODPERMLOTEVENCIDO != value)
                {
                    _pRODPERMLOTEVENCIDO = value;
                    OnPropertyChanged("PRODPERMLOTEVENCIDO");
                }
            }
        }
        private string _pRODPERMLOTEVENCIDO;
    
        [DataMember]
        public Nullable<int> TipoAssinCod
        {
            get { return _tipoAssinCod; }
            set
            {
                if (_tipoAssinCod != value)
                {
                    _tipoAssinCod = value;
                    OnPropertyChanged("TipoAssinCod");
                }
            }
        }
        private Nullable<int> _tipoAssinCod;
    
        [DataMember]
        public string GrupTensaoCod
        {
            get { return _grupTensaoCod; }
            set
            {
                if (_grupTensaoCod != value)
                {
                    _grupTensaoCod = value;
                    OnPropertyChanged("GrupTensaoCod");
                }
            }
        }
        private string _grupTensaoCod;
    
        [DataMember]
        public string ProdTpLigacao
        {
            get { return _prodTpLigacao; }
            set
            {
                if (_prodTpLigacao != value)
                {
                    _prodTpLigacao = value;
                    OnPropertyChanged("ProdTpLigacao");
                }
            }
        }
        private string _prodTpLigacao;
    
        [DataMember]
        public Nullable<int> IDCodigoConsumo
        {
            get { return _iDCodigoConsumo; }
            set
            {
                if (_iDCodigoConsumo != value)
                {
                    _iDCodigoConsumo = value;
                    OnPropertyChanged("IDCodigoConsumo");
                }
            }
        }
        private Nullable<int> _iDCodigoConsumo;
    
        [DataMember]
        public Nullable<int> IdTipoProdPpcp
        {
            get { return _idTipoProdPpcp; }
            set
            {
                if (_idTipoProdPpcp != value)
                {
                    _idTipoProdPpcp = value;
                    OnPropertyChanged("IdTipoProdPpcp");
                }
            }
        }
        private Nullable<int> _idTipoProdPpcp;
    
        [DataMember]
        public string ProdSegRocha
        {
            get { return _prodSegRocha; }
            set
            {
                if (_prodSegRocha != value)
                {
                    _prodSegRocha = value;
                    OnPropertyChanged("ProdSegRocha");
                }
            }
        }
        private string _prodSegRocha;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public CIDADE CIDADE
        {
            get { return _cIDADE; }
            set
            {
                if (!ReferenceEquals(_cIDADE, value))
                {
                    var previousValue = _cIDADE;
                    _cIDADE = value;
                    FixupCIDADE(previousValue);
                    OnNavigationPropertyChanged("CIDADE");
                }
            }
        }
        private CIDADE _cIDADE;
    
        [DataMember]
        public TrackableCollection<CTRL_LOTE> CTRL_LOTE
        {
            get
            {
                if (_cTRL_LOTE == null)
                {
                    _cTRL_LOTE = new TrackableCollection<CTRL_LOTE>();
                    _cTRL_LOTE.CollectionChanged += FixupCTRL_LOTE;
                }
                return _cTRL_LOTE;
            }
            set
            {
                if (!ReferenceEquals(_cTRL_LOTE, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_cTRL_LOTE != null)
                    {
                        _cTRL_LOTE.CollectionChanged -= FixupCTRL_LOTE;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (CTRL_LOTE item in _cTRL_LOTE)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _cTRL_LOTE = value;
                    if (_cTRL_LOTE != null)
                    {
                        _cTRL_LOTE.CollectionChanged += FixupCTRL_LOTE;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (CTRL_LOTE item in _cTRL_LOTE)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("CTRL_LOTE");
                }
            }
        }
        private TrackableCollection<CTRL_LOTE> _cTRL_LOTE;
    
        [DataMember]
        public TrackableCollection<FIC_TEC_PROD> FIC_TEC_PROD
        {
            get
            {
                if (_fIC_TEC_PROD == null)
                {
                    _fIC_TEC_PROD = new TrackableCollection<FIC_TEC_PROD>();
                    _fIC_TEC_PROD.CollectionChanged += FixupFIC_TEC_PROD;
                }
                return _fIC_TEC_PROD;
            }
            set
            {
                if (!ReferenceEquals(_fIC_TEC_PROD, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_fIC_TEC_PROD != null)
                    {
                        _fIC_TEC_PROD.CollectionChanged -= FixupFIC_TEC_PROD;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (FIC_TEC_PROD item in _fIC_TEC_PROD)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _fIC_TEC_PROD = value;
                    if (_fIC_TEC_PROD != null)
                    {
                        _fIC_TEC_PROD.CollectionChanged += FixupFIC_TEC_PROD;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (FIC_TEC_PROD item in _fIC_TEC_PROD)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("FIC_TEC_PROD");
                }
            }
        }
        private TrackableCollection<FIC_TEC_PROD> _fIC_TEC_PROD;
    
        [DataMember]
        public TrackableCollection<ITEM_CTRL_INV1> ITEM_CTRL_INV1
        {
            get
            {
                if (_iTEM_CTRL_INV1 == null)
                {
                    _iTEM_CTRL_INV1 = new TrackableCollection<ITEM_CTRL_INV1>();
                    _iTEM_CTRL_INV1.CollectionChanged += FixupITEM_CTRL_INV1;
                }
                return _iTEM_CTRL_INV1;
            }
            set
            {
                if (!ReferenceEquals(_iTEM_CTRL_INV1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_iTEM_CTRL_INV1 != null)
                    {
                        _iTEM_CTRL_INV1.CollectionChanged -= FixupITEM_CTRL_INV1;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (ITEM_CTRL_INV1 item in _iTEM_CTRL_INV1)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _iTEM_CTRL_INV1 = value;
                    if (_iTEM_CTRL_INV1 != null)
                    {
                        _iTEM_CTRL_INV1.CollectionChanged += FixupITEM_CTRL_INV1;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (ITEM_CTRL_INV1 item in _iTEM_CTRL_INV1)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("ITEM_CTRL_INV1");
                }
            }
        }
        private TrackableCollection<ITEM_CTRL_INV1> _iTEM_CTRL_INV1;
    
        [DataMember]
        public TrackableCollection<PRODUTO1> PRODUTO11
        {
            get
            {
                if (_pRODUTO11 == null)
                {
                    _pRODUTO11 = new TrackableCollection<PRODUTO1>();
                    _pRODUTO11.CollectionChanged += FixupPRODUTO11;
                }
                return _pRODUTO11;
            }
            set
            {
                if (!ReferenceEquals(_pRODUTO11, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pRODUTO11 != null)
                    {
                        _pRODUTO11.CollectionChanged -= FixupPRODUTO11;
                    }
                    _pRODUTO11 = value;
                    if (_pRODUTO11 != null)
                    {
                        _pRODUTO11.CollectionChanged += FixupPRODUTO11;
                    }
                    OnNavigationPropertyChanged("PRODUTO11");
                }
            }
        }
        private TrackableCollection<PRODUTO1> _pRODUTO11;
    
        [DataMember]
        public PRODUTO1 PRODUTO12
        {
            get { return _pRODUTO12; }
            set
            {
                if (!ReferenceEquals(_pRODUTO12, value))
                {
                    var previousValue = _pRODUTO12;
                    _pRODUTO12 = value;
                    FixupPRODUTO12(previousValue);
                    OnNavigationPropertyChanged("PRODUTO12");
                }
            }
        }
        private PRODUTO1 _pRODUTO12;
    
        [DataMember]
        public PRODUTO PRODUTO
        {
            get { return _pRODUTO; }
            set
            {
                if (!ReferenceEquals(_pRODUTO, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (ProdCodEstr != value.ProdCodEstr)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _pRODUTO;
                    _pRODUTO = value;
                    FixupPRODUTO(previousValue);
                    OnNavigationPropertyChanged("PRODUTO");
                }
            }
        }
        private PRODUTO _pRODUTO;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            CIDADE = null;
            CTRL_LOTE.Clear();
            FIC_TEC_PROD.Clear();
            ITEM_CTRL_INV1.Clear();
            PRODUTO11.Clear();
            PRODUTO12 = null;
            PRODUTO = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupCIDADE(CIDADE previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PRODUTO1.Contains(this))
            {
                previousValue.PRODUTO1.Remove(this);
            }
    
            if (CIDADE != null)
            {
                if (!CIDADE.PRODUTO1.Contains(this))
                {
                    CIDADE.PRODUTO1.Add(this);
                }
    
                ProdCidCodBloq = CIDADE.CidCod;
            }
            else if (!skipKeys)
            {
                ProdCidCodBloq = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("CIDADE")
                    && (ChangeTracker.OriginalValues["CIDADE"] == CIDADE))
                {
                    ChangeTracker.OriginalValues.Remove("CIDADE");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("CIDADE", previousValue);
                }
                if (CIDADE != null && !CIDADE.ChangeTracker.ChangeTrackingEnabled)
                {
                    CIDADE.StartTracking();
                }
            }
        }
    
        private void FixupPRODUTO12(PRODUTO1 previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PRODUTO11.Contains(this))
            {
                previousValue.PRODUTO11.Remove(this);
            }
    
            if (PRODUTO12 != null)
            {
                if (!PRODUTO12.PRODUTO11.Contains(this))
                {
                    PRODUTO12.PRODUTO11.Add(this);
                }
    
                ProdCodEstrProdPaiProj = PRODUTO12.ProdCodEstr;
            }
            else if (!skipKeys)
            {
                ProdCodEstrProdPaiProj = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PRODUTO12")
                    && (ChangeTracker.OriginalValues["PRODUTO12"] == PRODUTO12))
                {
                    ChangeTracker.OriginalValues.Remove("PRODUTO12");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PRODUTO12", previousValue);
                }
                if (PRODUTO12 != null && !PRODUTO12.ChangeTracker.ChangeTrackingEnabled)
                {
                    PRODUTO12.StartTracking();
                }
            }
        }
    
        private void FixupPRODUTO(PRODUTO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.PRODUTO14, this))
            {
                previousValue.PRODUTO14 = null;
            }
    
            if (PRODUTO != null)
            {
                PRODUTO.PRODUTO14 = this;
                ProdCodEstr = PRODUTO.ProdCodEstr;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PRODUTO")
                    && (ChangeTracker.OriginalValues["PRODUTO"] == PRODUTO))
                {
                    ChangeTracker.OriginalValues.Remove("PRODUTO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PRODUTO", previousValue);
                }
                if (PRODUTO != null && !PRODUTO.ChangeTracker.ChangeTrackingEnabled)
                {
                    PRODUTO.StartTracking();
                }
            }
        }
    
        private void FixupCTRL_LOTE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CTRL_LOTE item in e.NewItems)
                {
                    item.PRODUTO1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("CTRL_LOTE", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CTRL_LOTE item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUTO1, this))
                    {
                        item.PRODUTO1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("CTRL_LOTE", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupFIC_TEC_PROD(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FIC_TEC_PROD item in e.NewItems)
                {
                    item.PRODUTO1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FIC_TEC_PROD", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FIC_TEC_PROD item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUTO1, this))
                    {
                        item.PRODUTO1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FIC_TEC_PROD", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupITEM_CTRL_INV1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ITEM_CTRL_INV1 item in e.NewItems)
                {
                    item.PRODUTO1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ITEM_CTRL_INV1", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ITEM_CTRL_INV1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUTO1, this))
                    {
                        item.PRODUTO1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ITEM_CTRL_INV1", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupPRODUTO11(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PRODUTO1 item in e.NewItems)
                {
                    item.PRODUTO12 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PRODUTO11", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PRODUTO1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.PRODUTO12, this))
                    {
                        item.PRODUTO12 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PRODUTO11", item);
                    }
                }
            }
        }

        #endregion

    }
}
