//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace MvcAppHylinedoBrasilMobile.Models.bdApolo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CIDADE))]
    [KnownType(typeof(ROTA_ENTREGA))]
    [KnownType(typeof(ROTA_ENTREGA_CID_ENT))]
    public partial class ROTA_ENTREGA_CID: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string RotaEntregaCod
        {
            get { return _rotaEntregaCod; }
            set
            {
                if (_rotaEntregaCod != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RotaEntregaCod' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (ROTA_ENTREGA != null && ROTA_ENTREGA.RotaEntregaCod != value)
                        {
                            ROTA_ENTREGA = null;
                        }
                    }
                    _rotaEntregaCod = value;
                    OnPropertyChanged("RotaEntregaCod");
                }
            }
        }
        private string _rotaEntregaCod;
    
        [DataMember]
        public string CidCod
        {
            get { return _cidCod; }
            set
            {
                if (_cidCod != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CidCod' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (CIDADE != null && CIDADE.CidCod != value)
                        {
                            CIDADE = null;
                        }
                    }
                    _cidCod = value;
                    OnPropertyChanged("CidCod");
                }
            }
        }
        private string _cidCod;
    
        [DataMember]
        public Nullable<short> RotaEntregaCidSeq
        {
            get { return _rotaEntregaCidSeq; }
            set
            {
                if (_rotaEntregaCidSeq != value)
                {
                    _rotaEntregaCidSeq = value;
                    OnPropertyChanged("RotaEntregaCidSeq");
                }
            }
        }
        private Nullable<short> _rotaEntregaCidSeq;
    
        [DataMember]
        public Nullable<decimal> RotaEntregaCidQtdKm
        {
            get { return _rotaEntregaCidQtdKm; }
            set
            {
                if (_rotaEntregaCidQtdKm != value)
                {
                    _rotaEntregaCidQtdKm = value;
                    OnPropertyChanged("RotaEntregaCidQtdKm");
                }
            }
        }
        private Nullable<decimal> _rotaEntregaCidQtdKm;
    
        [DataMember]
        public Nullable<short> RotaEntregaCidQtdPedag
        {
            get { return _rotaEntregaCidQtdPedag; }
            set
            {
                if (_rotaEntregaCidQtdPedag != value)
                {
                    _rotaEntregaCidQtdPedag = value;
                    OnPropertyChanged("RotaEntregaCidQtdPedag");
                }
            }
        }
        private Nullable<short> _rotaEntregaCidQtdPedag;
    
        [DataMember]
        public Nullable<decimal> RotaEntregaCidValPedagEixo
        {
            get { return _rotaEntregaCidValPedagEixo; }
            set
            {
                if (_rotaEntregaCidValPedagEixo != value)
                {
                    _rotaEntregaCidValPedagEixo = value;
                    OnPropertyChanged("RotaEntregaCidValPedagEixo");
                }
            }
        }
        private Nullable<decimal> _rotaEntregaCidValPedagEixo;
    
        [DataMember]
        public string RotaEntregaCidPartCalcHabit
        {
            get { return _rotaEntregaCidPartCalcHabit; }
            set
            {
                if (_rotaEntregaCidPartCalcHabit != value)
                {
                    _rotaEntregaCidPartCalcHabit = value;
                    OnPropertyChanged("RotaEntregaCidPartCalcHabit");
                }
            }
        }
        private string _rotaEntregaCidPartCalcHabit;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public CIDADE CIDADE
        {
            get { return _cIDADE; }
            set
            {
                if (!ReferenceEquals(_cIDADE, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (CidCod != value.CidCod)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _cIDADE;
                    _cIDADE = value;
                    FixupCIDADE(previousValue);
                    OnNavigationPropertyChanged("CIDADE");
                }
            }
        }
        private CIDADE _cIDADE;
    
        [DataMember]
        public ROTA_ENTREGA ROTA_ENTREGA
        {
            get { return _rOTA_ENTREGA; }
            set
            {
                if (!ReferenceEquals(_rOTA_ENTREGA, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (RotaEntregaCod != value.RotaEntregaCod)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _rOTA_ENTREGA;
                    _rOTA_ENTREGA = value;
                    FixupROTA_ENTREGA(previousValue);
                    OnNavigationPropertyChanged("ROTA_ENTREGA");
                }
            }
        }
        private ROTA_ENTREGA _rOTA_ENTREGA;
    
        [DataMember]
        public TrackableCollection<ROTA_ENTREGA_CID_ENT> ROTA_ENTREGA_CID_ENT
        {
            get
            {
                if (_rOTA_ENTREGA_CID_ENT == null)
                {
                    _rOTA_ENTREGA_CID_ENT = new TrackableCollection<ROTA_ENTREGA_CID_ENT>();
                    _rOTA_ENTREGA_CID_ENT.CollectionChanged += FixupROTA_ENTREGA_CID_ENT;
                }
                return _rOTA_ENTREGA_CID_ENT;
            }
            set
            {
                if (!ReferenceEquals(_rOTA_ENTREGA_CID_ENT, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_rOTA_ENTREGA_CID_ENT != null)
                    {
                        _rOTA_ENTREGA_CID_ENT.CollectionChanged -= FixupROTA_ENTREGA_CID_ENT;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (ROTA_ENTREGA_CID_ENT item in _rOTA_ENTREGA_CID_ENT)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _rOTA_ENTREGA_CID_ENT = value;
                    if (_rOTA_ENTREGA_CID_ENT != null)
                    {
                        _rOTA_ENTREGA_CID_ENT.CollectionChanged += FixupROTA_ENTREGA_CID_ENT;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (ROTA_ENTREGA_CID_ENT item in _rOTA_ENTREGA_CID_ENT)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("ROTA_ENTREGA_CID_ENT");
                }
            }
        }
        private TrackableCollection<ROTA_ENTREGA_CID_ENT> _rOTA_ENTREGA_CID_ENT;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            CIDADE = null;
            ROTA_ENTREGA = null;
            ROTA_ENTREGA_CID_ENT.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupCIDADE(CIDADE previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ROTA_ENTREGA_CID.Contains(this))
            {
                previousValue.ROTA_ENTREGA_CID.Remove(this);
            }
    
            if (CIDADE != null)
            {
                if (!CIDADE.ROTA_ENTREGA_CID.Contains(this))
                {
                    CIDADE.ROTA_ENTREGA_CID.Add(this);
                }
    
                CidCod = CIDADE.CidCod;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("CIDADE")
                    && (ChangeTracker.OriginalValues["CIDADE"] == CIDADE))
                {
                    ChangeTracker.OriginalValues.Remove("CIDADE");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("CIDADE", previousValue);
                }
                if (CIDADE != null && !CIDADE.ChangeTracker.ChangeTrackingEnabled)
                {
                    CIDADE.StartTracking();
                }
            }
        }
    
        private void FixupROTA_ENTREGA(ROTA_ENTREGA previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ROTA_ENTREGA_CID.Contains(this))
            {
                previousValue.ROTA_ENTREGA_CID.Remove(this);
            }
    
            if (ROTA_ENTREGA != null)
            {
                if (!ROTA_ENTREGA.ROTA_ENTREGA_CID.Contains(this))
                {
                    ROTA_ENTREGA.ROTA_ENTREGA_CID.Add(this);
                }
    
                RotaEntregaCod = ROTA_ENTREGA.RotaEntregaCod;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ROTA_ENTREGA")
                    && (ChangeTracker.OriginalValues["ROTA_ENTREGA"] == ROTA_ENTREGA))
                {
                    ChangeTracker.OriginalValues.Remove("ROTA_ENTREGA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ROTA_ENTREGA", previousValue);
                }
                if (ROTA_ENTREGA != null && !ROTA_ENTREGA.ChangeTracker.ChangeTrackingEnabled)
                {
                    ROTA_ENTREGA.StartTracking();
                }
            }
        }
    
        private void FixupROTA_ENTREGA_CID_ENT(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ROTA_ENTREGA_CID_ENT item in e.NewItems)
                {
                    item.ROTA_ENTREGA_CID = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ROTA_ENTREGA_CID_ENT", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ROTA_ENTREGA_CID_ENT item in e.OldItems)
                {
                    if (ReferenceEquals(item.ROTA_ENTREGA_CID, this))
                    {
                        item.ROTA_ENTREGA_CID = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ROTA_ENTREGA_CID_ENT", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
