//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace MvcAppHyLinedoBrasil.EntityWebForms.HATCHERY_EGG_DATA
{
    [DataContract(IsReference = true)]
    public partial class HATCHERY_FLOCK_SETTER_DATA: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public string Hatch_Loc
        {
            get { return _hatch_Loc; }
            set
            {
                if (_hatch_Loc != value)
                {
                    _hatch_Loc = value;
                    OnPropertyChanged("Hatch_Loc");
                }
            }
        }
        private string _hatch_Loc;
    
        [DataMember]
        public Nullable<System.DateTime> Set_date
        {
            get { return _set_date; }
            set
            {
                if (_set_date != value)
                {
                    _set_date = value;
                    OnPropertyChanged("Set_date");
                }
            }
        }
        private Nullable<System.DateTime> _set_date;
    
        [DataMember]
        public string Flock_id
        {
            get { return _flock_id; }
            set
            {
                if (_flock_id != value)
                {
                    _flock_id = value;
                    OnPropertyChanged("Flock_id");
                }
            }
        }
        private string _flock_id;
    
        [DataMember]
        public string NumLote
        {
            get { return _numLote; }
            set
            {
                if (_numLote != value)
                {
                    _numLote = value;
                    OnPropertyChanged("NumLote");
                }
            }
        }
        private string _numLote;
    
        [DataMember]
        public string Setter
        {
            get { return _setter; }
            set
            {
                if (_setter != value)
                {
                    _setter = value;
                    OnPropertyChanged("Setter");
                }
            }
        }
        private string _setter;
    
        [DataMember]
        public string Hatcher
        {
            get { return _hatcher; }
            set
            {
                if (_hatcher != value)
                {
                    _hatcher = value;
                    OnPropertyChanged("Hatcher");
                }
            }
        }
        private string _hatcher;
    
        [DataMember]
        public string ClassOvo
        {
            get { return _classOvo; }
            set
            {
                if (_classOvo != value)
                {
                    _classOvo = value;
                    OnPropertyChanged("ClassOvo");
                }
            }
        }
        private string _classOvo;
    
        [DataMember]
        public Nullable<int> Eliminado
        {
            get { return _eliminado; }
            set
            {
                if (_eliminado != value)
                {
                    _eliminado = value;
                    OnPropertyChanged("Eliminado");
                }
            }
        }
        private Nullable<int> _eliminado;
    
        [DataMember]
        public Nullable<int> Morto
        {
            get { return _morto; }
            set
            {
                if (_morto != value)
                {
                    _morto = value;
                    OnPropertyChanged("Morto");
                }
            }
        }
        private Nullable<int> _morto;
    
        [DataMember]
        public Nullable<int> Macho
        {
            get { return _macho; }
            set
            {
                if (_macho != value)
                {
                    _macho = value;
                    OnPropertyChanged("Macho");
                }
            }
        }
        private Nullable<int> _macho;
    
        [DataMember]
        public Nullable<int> Pintos_Vendaveis
        {
            get { return _pintos_Vendaveis; }
            set
            {
                if (_pintos_Vendaveis != value)
                {
                    _pintos_Vendaveis = value;
                    OnPropertyChanged("Pintos_Vendaveis");
                }
            }
        }
        private Nullable<int> _pintos_Vendaveis;
    
        [DataMember]
        public Nullable<int> Refugo
        {
            get { return _refugo; }
            set
            {
                if (_refugo != value)
                {
                    _refugo = value;
                    OnPropertyChanged("Refugo");
                }
            }
        }
        private Nullable<int> _refugo;
    
        [DataMember]
        public Nullable<int> Pinto_Terceira
        {
            get { return _pinto_Terceira; }
            set
            {
                if (_pinto_Terceira != value)
                {
                    _pinto_Terceira = value;
                    OnPropertyChanged("Pinto_Terceira");
                }
            }
        }
        private Nullable<int> _pinto_Terceira;
    
        [DataMember]
        public Nullable<int> Qtde_Incubada
        {
            get { return _qtde_Incubada; }
            set
            {
                if (_qtde_Incubada != value)
                {
                    _qtde_Incubada = value;
                    OnPropertyChanged("Qtde_Incubada");
                }
            }
        }
        private Nullable<int> _qtde_Incubada;
    
        [DataMember]
        public Nullable<System.DateTime> DataRetiradaReal
        {
            get { return _dataRetiradaReal; }
            set
            {
                if (_dataRetiradaReal != value)
                {
                    _dataRetiradaReal = value;
                    OnPropertyChanged("DataRetiradaReal");
                }
            }
        }
        private Nullable<System.DateTime> _dataRetiradaReal;
    
        [DataMember]
        public string Horario_01_Retirada
        {
            get { return _horario_01_Retirada; }
            set
            {
                if (_horario_01_Retirada != value)
                {
                    _horario_01_Retirada = value;
                    OnPropertyChanged("Horario_01_Retirada");
                }
            }
        }
        private string _horario_01_Retirada;
    
        [DataMember]
        public Nullable<int> Qtde_01_Retirada
        {
            get { return _qtde_01_Retirada; }
            set
            {
                if (_qtde_01_Retirada != value)
                {
                    _qtde_01_Retirada = value;
                    OnPropertyChanged("Qtde_01_Retirada");
                }
            }
        }
        private Nullable<int> _qtde_01_Retirada;
    
        [DataMember]
        public string Horario_02_Retirada
        {
            get { return _horario_02_Retirada; }
            set
            {
                if (_horario_02_Retirada != value)
                {
                    _horario_02_Retirada = value;
                    OnPropertyChanged("Horario_02_Retirada");
                }
            }
        }
        private string _horario_02_Retirada;
    
        [DataMember]
        public Nullable<int> Qtde_02_Retirada
        {
            get { return _qtde_02_Retirada; }
            set
            {
                if (_qtde_02_Retirada != value)
                {
                    _qtde_02_Retirada = value;
                    OnPropertyChanged("Qtde_02_Retirada");
                }
            }
        }
        private Nullable<int> _qtde_02_Retirada;
    
        [DataMember]
        public string Variety
        {
            get { return _variety; }
            set
            {
                if (_variety != value)
                {
                    _variety = value;
                    OnPropertyChanged("Variety");
                }
            }
        }
        private string _variety;
    
        [DataMember]
        public Nullable<int> De0a4
        {
            get { return _de0a4; }
            set
            {
                if (_de0a4 != value)
                {
                    _de0a4 = value;
                    OnPropertyChanged("De0a4");
                }
            }
        }
        private Nullable<int> _de0a4;
    
        [DataMember]
        public Nullable<int> De5a12
        {
            get { return _de5a12; }
            set
            {
                if (_de5a12 != value)
                {
                    _de5a12 = value;
                    OnPropertyChanged("De5a12");
                }
            }
        }
        private Nullable<int> _de5a12;
    
        [DataMember]
        public Nullable<int> De13a17
        {
            get { return _de13a17; }
            set
            {
                if (_de13a17 != value)
                {
                    _de13a17 = value;
                    OnPropertyChanged("De13a17");
                }
            }
        }
        private Nullable<int> _de13a17;
    
        [DataMember]
        public Nullable<int> De18a21
        {
            get { return _de18a21; }
            set
            {
                if (_de18a21 != value)
                {
                    _de18a21 = value;
                    OnPropertyChanged("De18a21");
                }
            }
        }
        private Nullable<int> _de18a21;
    
        [DataMember]
        public Nullable<int> BicadoVivo
        {
            get { return _bicadoVivo; }
            set
            {
                if (_bicadoVivo != value)
                {
                    _bicadoVivo = value;
                    OnPropertyChanged("BicadoVivo");
                }
            }
        }
        private Nullable<int> _bicadoVivo;
    
        [DataMember]
        public Nullable<int> BicadoMorto
        {
            get { return _bicadoMorto; }
            set
            {
                if (_bicadoMorto != value)
                {
                    _bicadoMorto = value;
                    OnPropertyChanged("BicadoMorto");
                }
            }
        }
        private Nullable<int> _bicadoMorto;
    
        [DataMember]
        public Nullable<int> ContaminacaoBacteriana
        {
            get { return _contaminacaoBacteriana; }
            set
            {
                if (_contaminacaoBacteriana != value)
                {
                    _contaminacaoBacteriana = value;
                    OnPropertyChanged("ContaminacaoBacteriana");
                }
            }
        }
        private Nullable<int> _contaminacaoBacteriana;
    
        [DataMember]
        public Nullable<int> Fungo
        {
            get { return _fungo; }
            set
            {
                if (_fungo != value)
                {
                    _fungo = value;
                    OnPropertyChanged("Fungo");
                }
            }
        }
        private Nullable<int> _fungo;
    
        [DataMember]
        public Nullable<int> MalPosicionado
        {
            get { return _malPosicionado; }
            set
            {
                if (_malPosicionado != value)
                {
                    _malPosicionado = value;
                    OnPropertyChanged("MalPosicionado");
                }
            }
        }
        private Nullable<int> _malPosicionado;
    
        [DataMember]
        public Nullable<int> MalFormado
        {
            get { return _malFormado; }
            set
            {
                if (_malFormado != value)
                {
                    _malFormado = value;
                    OnPropertyChanged("MalFormado");
                }
            }
        }
        private Nullable<int> _malFormado;
    
        [DataMember]
        public Nullable<int> Infertil
        {
            get { return _infertil; }
            set
            {
                if (_infertil != value)
                {
                    _infertil = value;
                    OnPropertyChanged("Infertil");
                }
            }
        }
        private Nullable<int> _infertil;
    
        [DataMember]
        public Nullable<int> Inicial0a3
        {
            get { return _inicial0a3; }
            set
            {
                if (_inicial0a3 != value)
                {
                    _inicial0a3 = value;
                    OnPropertyChanged("Inicial0a3");
                }
            }
        }
        private Nullable<int> _inicial0a3;
    
        [DataMember]
        public Nullable<int> Inicial4a7
        {
            get { return _inicial4a7; }
            set
            {
                if (_inicial4a7 != value)
                {
                    _inicial4a7 = value;
                    OnPropertyChanged("Inicial4a7");
                }
            }
        }
        private Nullable<int> _inicial4a7;
    
        [DataMember]
        public Nullable<int> Media8a14
        {
            get { return _media8a14; }
            set
            {
                if (_media8a14 != value)
                {
                    _media8a14 = value;
                    OnPropertyChanged("Media8a14");
                }
            }
        }
        private Nullable<int> _media8a14;
    
        [DataMember]
        public Nullable<int> Tardia15a18
        {
            get { return _tardia15a18; }
            set
            {
                if (_tardia15a18 != value)
                {
                    _tardia15a18 = value;
                    OnPropertyChanged("Tardia15a18");
                }
            }
        }
        private Nullable<int> _tardia15a18;
    
        [DataMember]
        public Nullable<int> Tardia19a21
        {
            get { return _tardia19a21; }
            set
            {
                if (_tardia19a21 != value)
                {
                    _tardia19a21 = value;
                    OnPropertyChanged("Tardia19a21");
                }
            }
        }
        private Nullable<int> _tardia19a21;
    
        [DataMember]
        public Nullable<int> MaFormacaoCerebro
        {
            get { return _maFormacaoCerebro; }
            set
            {
                if (_maFormacaoCerebro != value)
                {
                    _maFormacaoCerebro = value;
                    OnPropertyChanged("MaFormacaoCerebro");
                }
            }
        }
        private Nullable<int> _maFormacaoCerebro;
    
        [DataMember]
        public Nullable<int> MaFormacaoVisceras
        {
            get { return _maFormacaoVisceras; }
            set
            {
                if (_maFormacaoVisceras != value)
                {
                    _maFormacaoVisceras = value;
                    OnPropertyChanged("MaFormacaoVisceras");
                }
            }
        }
        private Nullable<int> _maFormacaoVisceras;
    
        [DataMember]
        public Nullable<int> Hemorragico
        {
            get { return _hemorragico; }
            set
            {
                if (_hemorragico != value)
                {
                    _hemorragico = value;
                    OnPropertyChanged("Hemorragico");
                }
            }
        }
        private Nullable<int> _hemorragico;
    
        [DataMember]
        public Nullable<int> Anormalidade
        {
            get { return _anormalidade; }
            set
            {
                if (_anormalidade != value)
                {
                    _anormalidade = value;
                    OnPropertyChanged("Anormalidade");
                }
            }
        }
        private Nullable<int> _anormalidade;
    
        [DataMember]
        public Nullable<int> Amostra
        {
            get { return _amostra; }
            set
            {
                if (_amostra != value)
                {
                    _amostra = value;
                    OnPropertyChanged("Amostra");
                }
            }
        }
        private Nullable<int> _amostra;
    
        [DataMember]
        public Nullable<decimal> Infertilidade10Dias
        {
            get { return _infertilidade10Dias; }
            set
            {
                if (_infertilidade10Dias != value)
                {
                    _infertilidade10Dias = value;
                    OnPropertyChanged("Infertilidade10Dias");
                }
            }
        }
        private Nullable<decimal> _infertilidade10Dias;
    
        [DataMember]
        public Nullable<int> EliminadoCancelamento
        {
            get { return _eliminadoCancelamento; }
            set
            {
                if (_eliminadoCancelamento != value)
                {
                    _eliminadoCancelamento = value;
                    OnPropertyChanged("EliminadoCancelamento");
                }
            }
        }
        private Nullable<int> _eliminadoCancelamento;
    
        [DataMember]
        public Nullable<decimal> PerdaUmidade
        {
            get { return _perdaUmidade; }
            set
            {
                if (_perdaUmidade != value)
                {
                    _perdaUmidade = value;
                    OnPropertyChanged("PerdaUmidade");
                }
            }
        }
        private Nullable<decimal> _perdaUmidade;
    
        [DataMember]
        public Nullable<decimal> ChickYeld
        {
            get { return _chickYeld; }
            set
            {
                if (_chickYeld != value)
                {
                    _chickYeld = value;
                    OnPropertyChanged("ChickYeld");
                }
            }
        }
        private Nullable<decimal> _chickYeld;
    
        [DataMember]
        public Nullable<decimal> TempCloaca
        {
            get { return _tempCloaca; }
            set
            {
                if (_tempCloaca != value)
                {
                    _tempCloaca = value;
                    OnPropertyChanged("TempCloaca");
                }
            }
        }
        private Nullable<decimal> _tempCloaca;
    
        [DataMember]
        public Nullable<int> OvoVirado
        {
            get { return _ovoVirado; }
            set
            {
                if (_ovoVirado != value)
                {
                    _ovoVirado = value;
                    OnPropertyChanged("OvoVirado");
                }
            }
        }
        private Nullable<int> _ovoVirado;
    
        [DataMember]
        public Nullable<int> QuebradoTrincado
        {
            get { return _quebradoTrincado; }
            set
            {
                if (_quebradoTrincado != value)
                {
                    _quebradoTrincado = value;
                    OnPropertyChanged("QuebradoTrincado");
                }
            }
        }
        private Nullable<int> _quebradoTrincado;
    
        [DataMember]
        public string SetterEmbrio
        {
            get { return _setterEmbrio; }
            set
            {
                if (_setterEmbrio != value)
                {
                    _setterEmbrio = value;
                    OnPropertyChanged("SetterEmbrio");
                }
            }
        }
        private string _setterEmbrio;
    
        [DataMember]
        public string HatcherEmbrio
        {
            get { return _hatcherEmbrio; }
            set
            {
                if (_hatcherEmbrio != value)
                {
                    _hatcherEmbrio = value;
                    OnPropertyChanged("HatcherEmbrio");
                }
            }
        }
        private string _hatcherEmbrio;
    
        [DataMember]
        public Nullable<int> QtdeNascidos
        {
            get { return _qtdeNascidos; }
            set
            {
                if (_qtdeNascidos != value)
                {
                    _qtdeNascidos = value;
                    OnPropertyChanged("QtdeNascidos");
                }
            }
        }
        private Nullable<int> _qtdeNascidos;
    
        [DataMember]
        public Nullable<decimal> Peso
        {
            get { return _peso; }
            set
            {
                if (_peso != value)
                {
                    _peso = value;
                    OnPropertyChanged("Peso");
                }
            }
        }
        private Nullable<decimal> _peso;
    
        [DataMember]
        public Nullable<decimal> Uniformidade
        {
            get { return _uniformidade; }
            set
            {
                if (_uniformidade != value)
                {
                    _uniformidade = value;
                    OnPropertyChanged("Uniformidade");
                }
            }
        }
        private Nullable<decimal> _uniformidade;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
