//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace MvcAppHylinedoBrasilMobile.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(LOG_PedidoRacao))]
    [KnownType(typeof(LOG_PedidoRacao_Item))]
    public partial class LOG_PedidoRacao_Item_Aditivo: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public int IDLogPedidoRacao
        {
            get { return _iDLogPedidoRacao; }
            set
            {
                if (_iDLogPedidoRacao != value)
                {
                    ChangeTracker.RecordOriginalValue("IDLogPedidoRacao", _iDLogPedidoRacao);
                    if (!IsDeserializing)
                    {
                        if (LOG_PedidoRacao != null && LOG_PedidoRacao.ID != value)
                        {
                            LOG_PedidoRacao = null;
                        }
                    }
                    _iDLogPedidoRacao = value;
                    OnPropertyChanged("IDLogPedidoRacao");
                }
            }
        }
        private int _iDLogPedidoRacao;
    
        [DataMember]
        public int IDLogPedidoRacao_Item
        {
            get { return _iDLogPedidoRacao_Item; }
            set
            {
                if (_iDLogPedidoRacao_Item != value)
                {
                    ChangeTracker.RecordOriginalValue("IDLogPedidoRacao_Item", _iDLogPedidoRacao_Item);
                    if (!IsDeserializing)
                    {
                        if (LOG_PedidoRacao_Item != null && LOG_PedidoRacao_Item.ID != value)
                        {
                            LOG_PedidoRacao_Item = null;
                        }
                    }
                    _iDLogPedidoRacao_Item = value;
                    OnPropertyChanged("IDLogPedidoRacao_Item");
                }
            }
        }
        private int _iDLogPedidoRacao_Item;
    
        [DataMember]
        public int IDPedidoRacao
        {
            get { return _iDPedidoRacao; }
            set
            {
                if (_iDPedidoRacao != value)
                {
                    _iDPedidoRacao = value;
                    OnPropertyChanged("IDPedidoRacao");
                }
            }
        }
        private int _iDPedidoRacao;
    
        [DataMember]
        public int IDPedidoRacao_Item
        {
            get { return _iDPedidoRacao_Item; }
            set
            {
                if (_iDPedidoRacao_Item != value)
                {
                    _iDPedidoRacao_Item = value;
                    OnPropertyChanged("IDPedidoRacao_Item");
                }
            }
        }
        private int _iDPedidoRacao_Item;
    
        [DataMember]
        public int IDPedidoRacao_Item_Aditivo
        {
            get { return _iDPedidoRacao_Item_Aditivo; }
            set
            {
                if (_iDPedidoRacao_Item_Aditivo != value)
                {
                    _iDPedidoRacao_Item_Aditivo = value;
                    OnPropertyChanged("IDPedidoRacao_Item_Aditivo");
                }
            }
        }
        private int _iDPedidoRacao_Item_Aditivo;
    
        [DataMember]
        public string ProdCodEstr
        {
            get { return _prodCodEstr; }
            set
            {
                if (_prodCodEstr != value)
                {
                    _prodCodEstr = value;
                    OnPropertyChanged("ProdCodEstr");
                }
            }
        }
        private string _prodCodEstr;
    
        [DataMember]
        public Nullable<decimal> QtdeKgPorTon
        {
            get { return _qtdeKgPorTon; }
            set
            {
                if (_qtdeKgPorTon != value)
                {
                    _qtdeKgPorTon = value;
                    OnPropertyChanged("QtdeKgPorTon");
                }
            }
        }
        private Nullable<decimal> _qtdeKgPorTon;
    
        [DataMember]
        public Nullable<int> Sequencia
        {
            get { return _sequencia; }
            set
            {
                if (_sequencia != value)
                {
                    _sequencia = value;
                    OnPropertyChanged("Sequencia");
                }
            }
        }
        private Nullable<int> _sequencia;
    
        [DataMember]
        public Nullable<int> SeqItem
        {
            get { return _seqItem; }
            set
            {
                if (_seqItem != value)
                {
                    _seqItem = value;
                    OnPropertyChanged("SeqItem");
                }
            }
        }
        private Nullable<int> _seqItem;
    
        [DataMember]
        public string Operacao
        {
            get { return _operacao; }
            set
            {
                if (_operacao != value)
                {
                    _operacao = value;
                    OnPropertyChanged("Operacao");
                }
            }
        }
        private string _operacao;
    
        [DataMember]
        public string Origem
        {
            get { return _origem; }
            set
            {
                if (_origem != value)
                {
                    _origem = value;
                    OnPropertyChanged("Origem");
                }
            }
        }
        private string _origem;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public LOG_PedidoRacao LOG_PedidoRacao
        {
            get { return _lOG_PedidoRacao; }
            set
            {
                if (!ReferenceEquals(_lOG_PedidoRacao, value))
                {
                    var previousValue = _lOG_PedidoRacao;
                    _lOG_PedidoRacao = value;
                    FixupLOG_PedidoRacao(previousValue);
                    OnNavigationPropertyChanged("LOG_PedidoRacao");
                }
            }
        }
        private LOG_PedidoRacao _lOG_PedidoRacao;
    
        [DataMember]
        public LOG_PedidoRacao_Item LOG_PedidoRacao_Item
        {
            get { return _lOG_PedidoRacao_Item; }
            set
            {
                if (!ReferenceEquals(_lOG_PedidoRacao_Item, value))
                {
                    var previousValue = _lOG_PedidoRacao_Item;
                    _lOG_PedidoRacao_Item = value;
                    FixupLOG_PedidoRacao_Item(previousValue);
                    OnNavigationPropertyChanged("LOG_PedidoRacao_Item");
                }
            }
        }
        private LOG_PedidoRacao_Item _lOG_PedidoRacao_Item;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            LOG_PedidoRacao = null;
            LOG_PedidoRacao_Item = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupLOG_PedidoRacao(LOG_PedidoRacao previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.LOG_PedidoRacao_Item_Aditivo.Contains(this))
            {
                previousValue.LOG_PedidoRacao_Item_Aditivo.Remove(this);
            }
    
            if (LOG_PedidoRacao != null)
            {
                if (!LOG_PedidoRacao.LOG_PedidoRacao_Item_Aditivo.Contains(this))
                {
                    LOG_PedidoRacao.LOG_PedidoRacao_Item_Aditivo.Add(this);
                }
    
                IDLogPedidoRacao = LOG_PedidoRacao.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("LOG_PedidoRacao")
                    && (ChangeTracker.OriginalValues["LOG_PedidoRacao"] == LOG_PedidoRacao))
                {
                    ChangeTracker.OriginalValues.Remove("LOG_PedidoRacao");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("LOG_PedidoRacao", previousValue);
                }
                if (LOG_PedidoRacao != null && !LOG_PedidoRacao.ChangeTracker.ChangeTrackingEnabled)
                {
                    LOG_PedidoRacao.StartTracking();
                }
            }
        }
    
        private void FixupLOG_PedidoRacao_Item(LOG_PedidoRacao_Item previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.LOG_PedidoRacao_Item_Aditivo.Contains(this))
            {
                previousValue.LOG_PedidoRacao_Item_Aditivo.Remove(this);
            }
    
            if (LOG_PedidoRacao_Item != null)
            {
                if (!LOG_PedidoRacao_Item.LOG_PedidoRacao_Item_Aditivo.Contains(this))
                {
                    LOG_PedidoRacao_Item.LOG_PedidoRacao_Item_Aditivo.Add(this);
                }
    
                IDLogPedidoRacao_Item = LOG_PedidoRacao_Item.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("LOG_PedidoRacao_Item")
                    && (ChangeTracker.OriginalValues["LOG_PedidoRacao_Item"] == LOG_PedidoRacao_Item))
                {
                    ChangeTracker.OriginalValues.Remove("LOG_PedidoRacao_Item");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("LOG_PedidoRacao_Item", previousValue);
                }
                if (LOG_PedidoRacao_Item != null && !LOG_PedidoRacao_Item.ChangeTracker.ChangeTrackingEnabled)
                {
                    LOG_PedidoRacao_Item.StartTracking();
                }
            }
        }

        #endregion

    }
}
